### ISSUE TITLE
AllExpensesPage

### ISSUE THREAD

**Issue by bellaignacio** [bellaignacio/splitwise-clone-flask#52]
**TopNavigationBar**

**LeftNavigationBar**

**RightSummaryBar**

**MainHeader**

**Main Content**
* in chronological order (most recent on the top)
* Expense headers - click expands Expense Details section
  * expenses user created with 1 person: {date} {receipt-img} {description} you paid: {amount} you lent {friend}: {amount - amount_due}
  * expenses user created with 2+ people: {date} {receipt-img} {description} you paid: {amount} you lent: {amount - amount_due} 
  * expenses user gets charged: {date} {receipt-img} {description} {friend} paid: {amount} {friend} lent you: {amount_due}
  * red X on hover - click opens Delete Expense alert
* Payment headers - click expands Payment Details section
  * user makes payment: {dollar-img} {name} paid {friend} {amount}
  * user receives payment: {dollar-img} {friend} paid {name} {amount}
  * red X on hover - click opens Delete Payment alert

**Comment by bellaignacio** [comment]
@Dmytro-Yakovenko it might make better sense for me to complete this component since it is almost identical to the FriendPage.
meanwhile, you can continue to style the components you've already started

**Comment by Dmytro-Yakovenko** [comment]
Sure, no problem 
Thank you for your help
